"""empty message

Revision ID: 59c5dc15aaf6
Revises: 9ffb1e08a62f
Create Date: 2021-08-01 15:11:04.363435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c5dc15aaf6'
down_revision = '9ffb1e08a62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String())))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String())))
    op.execute('''ALTER TABLE "Artist"
                    ALTER COLUMN genres SET DEFAULT '{}';''')
    op.execute('''ALTER TABLE "Venue"
                    ALTER COLUMN genres SET DEFAULT '{}';''')
    op.execute('''UPDATE "Artist" set genres = '{}';''')
    op.execute('''UPDATE "Venue" set genres = '{}';''')
                    
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    pass
    # ### end Alembic commands ###
